# Generated by Django 3.0.5 on 2020-05-03 16:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("about", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "User",},
        ),
    ]
