# Generated by Django 3.0.5 on 2020-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("greeting", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
