# Generated by Django 3.0.6 on 2020-05-11 13:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("about", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Main Page",},
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("greeting", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "User Info",},
        ),
    ]
