# Generated by Django 3.0.5 on 2020-04-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo", options={"verbose_name_plural": "User Info"},
        ),
    ]
