# Generated by Django 3.0.5 on 2020-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                related_name="projects", to="resume.Technology"
            ),
        ),
    ]
