# Generated by Django 3.0.5 on 2020-04-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('resume', '0002_auto_20200420_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities',
                                   to='resume.Project')),
            ],
        ),
    ]
